/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jpn_techbooster_sample_nativesample2_Main */

#ifndef _Included_org_jpn_techbooster_sample_nativesample2_Main
#define _Included_org_jpn_techbooster_sample_nativesample2_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jpn_techbooster_sample_nativesample2_Main
 * Method:    nativeBinarization
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_org_jpn_techbooster_sample_nativesample2_Main_nativeBinarization
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
